INSERT INTO compliments (compliment, type, created, used) VALUES
('Your eyes sparkle like rootbeer in the sun.', 'custom', DateTime('now'), null),
('You are super hot skater chick.', 'custom', DateTime('now'), null),
('Of all of the people I know from California, you''re my favorite', 'custom', DateTime('now'), null),
('If you wen to Africa, you''d become famous as the coolest person in Africa', 'custom', DateTime('now'), null),
('You''d be a horrible sumo wrestler because you''re so skinny', 'custom', DateTime('now'), null),
('If I had to choose between hanging out with you and President Nelson, it would be a really hard choice.', 'custom', DateTime('now'), null),
('You''re my favorite person to go hiking with.', 'custom', DateTime('now'), null),
('If I wrote a book, I''d want you to be my editor', 'custom', DateTime('now'), null),
('You''re an amazing writer.', 'custom', DateTime('now'), null),
('Your brain is sexy.', 'custom', DateTime('now'), null),
('I like venting to you about my problems.', 'custom', DateTime('now'), null),
('If you wrote a book, I''d read it.', 'custom', DateTime('now'), null),
('I love that you are so responsible with money', 'custom', DateTime('now'), null),
('I like your butt', 'custom', DateTime('now'), null),
('I like you because you are so adventurous and like to do fun things!', 'custom', DateTime('now'), null),
('You smell the exact opposite of a really smelly swamp.', 'custom', DateTime('now'), null),
('If I were playing ''bigger or better'' and you were the item, I''d have to find something bigger because there''s nothing better than you!', 'custom', DateTime('now'), null),
('Your hair is silkier than a silkworm''s coocoon.', 'custom', DateTime('now'), null),
('I like fixing things at your house because I like you.', 'custom', DateTime('now'), null),
('You''re better than me at bananagrams', 'custom', DateTime('now'), null),
('There is absolutely nothing annoying about the sound of your voice.', 'custom', DateTime('now'), null),
('If you were a telemarketer I''d talk to you.', 'custom', DateTime('now'), null),
('You care so much about people and I really admire that.', 'custom', DateTime('now'), null),
('You''re winning at life. So hard', 'custom', DateTime('now'), null),
('If dating you meant I couldn''t ever eat chicken floutas again, it would be really hard to break up with you.', 'custom', DateTime('now'), null),
('You could open that jar of mayonnaise using only 3 fingers.', 'api', DateTime('now'), DateTime('now')),
('Strangers all wanna sit next to you on the bus.', 'api', DateTime('now'), DateTime('now')),
('Coworkers fantasizes about getting stuck in the elevator with you.', 'api', DateTime('now'), DateTime('now')),
('If Einstein could meet you, he''d be "mildly to moderately" intimidated.', 'api', DateTime('now'), DateTime('now')),
('At least two friends are going to name their child and/or goldfish after you.', 'api', DateTime('now'), null),
('socks + sandals + you = I''m into it.', 'api', DateTime('now'), DateTime('now')),
('Your ex thought about you this morning, then they thought about donuts.', 'api', DateTime('now'), null),
('You are freakishly good at thumb wars.', 'api', DateTime('now'), DateTime('now')),
('A 3rd tier cable network would totally create a television show about you.', 'api', DateTime('now'), DateTime('now')),
('The FBI tapped your phone just to hear the sound of your voice.', 'api', DateTime('now'), null),
('You remind everyone of kiwis- delicious and surprisingly fuzzy.', 'api', DateTime('now'), DateTime('now')),
('You never forget to fill the ice-cube tray.', 'api', DateTime('now'), null),
('People enjoy you accidentally touching their butt while putting on your seat-belt.', 'api', DateTime('now'), null),
('I’d give you the last piece of my gum even if I’d just ate garlic.', 'api', DateTime('now'), null),
('There was a high school rumor that you are a distant relative of Abraham Lincoln.', 'api', DateTime('now'), DateTime('now')),
('You could make up a weird religion or diet and everyone would follow it.', 'api', DateTime('now'), null),
('Your siblings are pissed that your photo is the star of your parent''s mantle.', 'api', DateTime('now'), null),
('Everyone at sleepovers thought you were the bravest during thunderstorms.', 'api', DateTime('now'), DateTime('now')),
('A doctor once saw your butt through the hospital gown. They approve!', 'api', DateTime('now'), null),
('Someone almost got a tattoo of your name once, but their mom talked them out of it.', 'api', DateTime('now'), null),
('You are your parent''s greatest accomplishment, unless they invented the "spork".', 'api', DateTime('now'), DateTime('now')),
('Some dudes hope you start a band so they can start a cover band of that band.', 'api', DateTime('now'), null),
('Your principal would call you to the office just to look cool.', 'api', DateTime('now'), null),
('Your allergies are some of the least embarrassing allergies.', 'api', DateTime('now'), DateTime('now')),
('Your handshake conveys intelligence, confidence and minor claminess.', 'api', DateTime('now'), DateTime('now')),
('Cops admire your ability to stay a perfect 3-5 miles above the speed limit.', 'api', DateTime('now'), DateTime('now')),
('You rarely have to go to the bathroom when you fly in the window seat.', 'api', DateTime('now'), null),
('Your roommate wants a lock of your hair but is afraid to ask.', 'api', DateTime('now'), DateTime('now')),
('Cockroaches, mice and other pests avoid your place out of respect.', 'api', DateTime('now'), DateTime('now')),
('Callers are intimidated by how funny your voicemail greeting is.', 'api', DateTime('now'), DateTime('now')),
('Kids think you are the “cool old person”.', 'api', DateTime('now'), null),
('People always think your jeggings are regular jeans.', 'api', DateTime('now'), DateTime('now')),
('80% of motorcycle gangs think you’d be a delightful sidecar.', 'api', DateTime('now'), null),
('Everyone at the laundromat thinks you have the cutest underwear.', 'api', DateTime('now'), null),
('People behind you at movies think you are the perfect height.', 'api', DateTime('now'), null),
('Your parents argue over which one of them you look like.', 'api', DateTime('now'), null),
('Sushi chefs are wowed by your chopstick dexterity.', 'api', DateTime('now'), DateTime('now')),
('You want the best for everyone...except Gary.', 'api', DateTime('now'), DateTime('now')),
('You are someone''s "the one that got away".', 'api', DateTime('now'), DateTime('now')),
('You look good in just about everything.', 'custom', DateTime('now'), null)
